In [4]:
import torch
import torch.nn as nn

In [5]:
prediction = torch.randn(4, 5)

In [6]:
label = torch.randn(4, 5)

In [17]:
mse = nn.MSELoss(reduction = 'mean')

In [18]:
loss = mse(prediction, label)

In [19]:
loss

tensor(1.4966)

In [21]:
((prediction-label)**2).mean()

tensor(1.4966)

In [23]:
prediction

tensor([[ 1.4887, -0.7490,  0.5201, -0.0183, -0.4082],
        [ 1.2248,  0.1142,  0.3067, -0.9239,  0.3208],
        [ 0.3845,  0.1011,  1.9612, -0.2891,  1.6361],
        [-0.2322,  0.6443,  0.0222,  1.0187,  0.1700]])

In [24]:
label = torch.zeros(4, 5).random_(0, 2)

In [25]:
label

tensor([[0., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0.],
        [0., 0., 1., 1., 0.],
        [0., 1., 1., 1., 1.]])

In [27]:
sigmoid = nn.Sigmoid()

In [31]:
bce = nn.BCELoss(reduction = 'mean')

In [32]:
bce

BCELoss()

In [33]:
sigmoid(prediction)

tensor([[0.8159, 0.3210, 0.6272, 0.4954, 0.3993],
        [0.7729, 0.5285, 0.5761, 0.2842, 0.5795],
        [0.5950, 0.5253, 0.8767, 0.4282, 0.8370],
        [0.4422, 0.6557, 0.5056, 0.7347, 0.5424]])

In [34]:
bce(sigmoid(prediction), label)

tensor(0.8151)

In [36]:
bces = bce = nn.BCEWithLogitsLoss(reduction = 'mean')

In [37]:
bces(prediction, label)

tensor(0.8151)

In [38]:
# from schratch using lists (yes they are slow)

In [45]:
import numpy as np
x = prediction.numpy()
y = label.numpy()

In [47]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [56]:
x = sigmoid(x)
loss_values = []
# for every batch
for i in range(len(y)):
    batch_loss = []
    # compute loss for every element and append to batch_loss list
    for j in range(len(y[0])):
        if y[i][j] == 1:
            loss = -np.log(x[i][j])
        else:
            loss = -np.log(1-x[i][j])
        batch_loss.append(loss)
    loss_values.append(batch_loss)

print(np.mean(loss_values))

0.7464849
