In [1]:
import torch
import torch.nn as nn

In [2]:
layer = nn.Linear(5, 5)

In [3]:
layer.weight

Parameter containing:
tensor([[-0.2261, -0.1626,  0.2879,  0.3833,  0.4166],
        [-0.0075,  0.2420, -0.0953, -0.1869, -0.1561],
        [ 0.2992,  0.2055,  0.3184, -0.0184, -0.0202],
        [ 0.0596,  0.0414, -0.0782,  0.2480, -0.4390],
        [-0.4302,  0.0938,  0.4264,  0.4154, -0.1778]], requires_grad=True)

In [4]:
layer.weight.data

tensor([[-0.2261, -0.1626,  0.2879,  0.3833,  0.4166],
        [-0.0075,  0.2420, -0.0953, -0.1869, -0.1561],
        [ 0.2992,  0.2055,  0.3184, -0.0184, -0.0202],
        [ 0.0596,  0.0414, -0.0782,  0.2480, -0.4390],
        [-0.4302,  0.0938,  0.4264,  0.4154, -0.1778]])

In [6]:
nn.init.uniform_(layer.weight, a=0.0, b=3)

Parameter containing:
tensor([[1.5208, 1.5111, 1.3897, 1.4477, 1.1393],
        [2.9407, 0.0597, 2.8236, 0.5844, 2.9073],
        [2.6733, 2.1632, 2.1948, 1.2070, 0.5433],
        [2.2288, 0.0946, 2.1565, 1.6376, 0.8656],
        [0.6856, 2.6014, 0.3244, 2.3832, 2.7594]], requires_grad=True)

In [9]:
nn.init.normal_(layer.weight, mean=0.0, std=5.0)

Parameter containing:
tensor([[-6.0694,  0.2148, -2.9516,  9.9172, -1.6191],
        [ 6.9791,  3.7283, -3.0901,  1.1995, -6.2544],
        [ 9.2221,  5.5033, -1.1483,  6.7040, -9.6536],
        [ 4.6295, -3.0027,  7.8971,  3.0196, -9.5704],
        [ 1.9040,  3.3241, -1.8030,  1.0561,  1.1724]], requires_grad=True)

In [11]:
nn.init.constant_(layer.weight, 8)

Parameter containing:
tensor([[8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.]], requires_grad=True)

In [12]:
nn.init.zeros_(layer.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [14]:
layer.bias

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [15]:
nn.init.xavier_uniform_(layer.weight, gain=1.0)

Parameter containing:
tensor([[ 0.0556, -0.5919, -0.0126, -0.0458,  0.5056],
        [ 0.1110,  0.3311, -0.4147,  0.2398, -0.2740],
        [-0.6292, -0.0265,  0.1185, -0.1486, -0.2798],
        [ 0.4694,  0.1773,  0.3806, -0.0617,  0.1598],
        [ 0.6016, -0.3601,  0.5476,  0.5653,  0.6811]], requires_grad=True)

In [16]:
nn.init.xavier_normal_(layer.weight, gain=1.0)

Parameter containing:
tensor([[ 0.2042,  0.3754, -0.4550, -0.9629, -0.1855],
        [ 0.0181,  0.1498, -0.7687, -0.4300,  0.0608],
        [-0.5438, -0.3098, -0.5236,  0.3875, -0.2185],
        [-0.1101, -0.5735,  0.1975,  0.1284, -0.5305],
        [ 0.2480, -0.8304,  0.3206, -0.8253,  0.2510]], requires_grad=True)